=== drWebber/XML/knives.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="https://www.sitename.com/knives"
    xmlns:tns="https://www.sitename.com/knives" elementFormDefault="qualified">
    <element name="knives">
        <complexType>
            <sequence>
                <element name="knife" maxOccurs="unbounded">
                    <complexType>
                        <sequence>
                            <element name="type">
                                <simpleType>
                                    <restriction base="string">
                                        <pattern value="[A-z]\w+" />
                                    </restriction>
                                </simpleType>
                            </element>
                            <element name="handy">
                                <simpleType>
                                    <restriction base="string">
                                        <enumeration value="ONE_HANDED" />
                                        <enumeration value="TWO_HANDED" />
                                    </restriction>
                                </simpleType>
                            </element>
                            <element name="origin">
                                <simpleType>
                                    <restriction base="string">
                                        <pattern value="[A-z]+" />
                                    </restriction>
                                </simpleType>
                            </element>
                            <element name="visual">
                                <complexType>
                                    <all>
                                        <element name="blade">
                                            <complexType>
                                                <sequence>
                                                    <element name="length">
                                                        <simpleType>
                                                            <restriction base="integer">
                                                                <minInclusive value="10"/>
                                                                <maxInclusive value="1500"/>
                                                            </restriction>
                                                        </simpleType>
                                                    </element>
                                                    <element name="width">
                                                        <simpleType>
                                                            <restriction base="integer">
                                                                <minInclusive value="10"/>
                                                                <maxInclusive value="150"/>
                                                            </restriction>
                                                        </simpleType>
                                                    </element>
                                                    <element name="blade_material">
                                                        <simpleType>
                                                            <restriction base="string">
                                                                <enumeration value="STEEL" />
                                                                <enumeration value="CASTIRON" />
                                                                <enumeration value="COPPER" />
                                                                <enumeration value="BRONZE" />
                                                            </restriction>
                                                        </simpleType>
                                                    </element>
                                                    <element name="fuller" type="boolean" />
                                                </sequence>
                                            </complexType>
                                        </element>
                                        <element name="handle">
                                            <complexType>
                                                <sequence>
                                                    <element name="handle_material">
                                                        <simpleType>
                                                            <restriction base="string">
                                                                <enumeration value="WOOD" />
                                                                <enumeration value="PLASTIC" />
                                                                <enumeration value="METAL" />
                                                            </restriction>
                                                        </simpleType>
                                                    </element>
                                                    <element name="material_type" minOccurs="0">
                                                        <simpleType>
                                                            <restriction base="string">
                                                                <pattern value="[A-z]+" />
                                                            </restriction>
                                                        </simpleType>
                                                    </element>
                                                </sequence>
                                            </complexType>
                                        </element>
                                    </all>
                                </complexType>
                            </element>
                            <element name="value" type="boolean" />
                        </sequence>
                        <attribute name="id" type="integer" use="required"/>
                    </complexType>
                </element>
            </sequence>
        </complexType>
    </element>
</schema>

=== drWebber/XML/knives.xml
<?xml version="1.0" encoding="UTF-8"?>
<knives xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns="https://www.sitename.com/knives" xsi:schemaLocation="https://www.sitename.com/knives.xsd">
    <knife id="12345">
        <type>Knife</type>
        <handy>ONE_HANDED</handy>
        <origin>Belarus</origin>
        <visual>
            <blade>
                <length>215</length>
                <width>15</width>
                <blade_material>STEEL</blade_material>
                <fuller>true</fuller>
            </blade>
            <handle>
                <handle_material>WOOD</handle_material>
                <material_type>oak</material_type>
            </handle>
        </visual>
        <value>false</value>
    </knife>
    <knife id="23456">
        <type>Sabre</type>
        <handy>ONE_HANDED</handy>
        <origin>Russia</origin>
        <visual>
            <blade>
                <length>500</length>
                <width>20</width>
                <blade_material>STEEL</blade_material>
                <fuller>false</fuller>
            </blade>
            <handle>
                <handle_material>METAL</handle_material>
            </handle>
        </visual>
        <value>true</value>
    </knife>
    <knife id="34567">
        <type>Dagger</type>
        <handy>ONE_HANDED</handy>
        <origin>Belarus</origin>
        <visual>
            <blade>
                <length>300</length>
                <width>10</width>
                <blade_material>COPPER</blade_material>
                <fuller>true</fuller>
            </blade>
            <handle>
                <handle_material>WOOD</handle_material>
                <material_type>maple</material_type>
            </handle>
        </visual>
        <value>true</value>
    </knife>
    <knife id="45678">
        <type>Sword</type>
        <handy>TWO_HANDED</handy>
        <origin>Lithuania</origin>
        <visual>
            <blade>
                <length>600</length>
                <width>40</width>
                <blade_material>STEEL</blade_material>
                <fuller>false</fuller>
            </blade>
            <handle>
                <handle_material>METAL</handle_material>
            </handle>
        </visual>
        <value>true</value>
    </knife>
    <knife id="56789">
        <type>Knife</type>
        <handy>ONE_HANDED</handy>
        <origin>Poland</origin>
        <visual>
            <blade>
                <length>25</length>
                <width>15</width>
                <blade_material>BRONZE</blade_material>
                <fuller>false</fuller>
            </blade>
            <handle>
                <handle_material>PLASTIC</handle_material>
            </handle>
        </visual>
        <value>false</value>
    </knife>
</knives>
